name: Publish Dockerimage

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  Docker-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: grolimundachim/csp-report-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: build/Dockerfile
          tag_names: true